export const authConstant = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};
export const timeinConstant = {
  TIME_IN_REQUEST: 'TIME_IN_REQUEST',
  GET_TIME_SUCCESS: 'GET_TIME_SUCCESS',
  GET_TIME_FAIL: 'GET_TIME_FAIL',
};
